- hosts: localhost
  connection: local
  remote_user: root
  sudo: yes

  vars_prompt:
  - name: yum_update
    prompt: "Do you accept updates ?"
    private: no
    default: Y

  tasks:
  - name: Yum update packages
    yum: name=* state=latest
    when: yum_update == "Y"

  - name: Desabled SELinux
    replace: >-
      dest="/etc/selinux/config"
      regexp="SELINUX=enforcing"
      replace="SELINUX=disabled"
    
  - name: Install ZABBIX reopsitory
    yum: name={{ item }}
    with_items:
      - http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm

  - name: Install EDI services
    yum: name="{{ item }}" state=present
    with_items:
      - vsftpd
      - open-vm-tools

  - name: Backup vsftpd.conf
    command: cp /etc/vsftpd/vsftpd.conf /etc/vsftpd/vsftpd.conf.orig

  - name: chroot_listの作成
    command: echo -n > /etc/vsftpd/chroot_list
 
  - name: vsftpd setting
    # /etc/vsftpd/vsftpd.confの設定変更
    lineinfile:
      dest="/etc/vsftpd/vsftpd.conf"
      state=present
      backrefs=yes
      regexp='{{ item.regexp }}'
      line='{{ item.line }}'
    with_items:
      - regexp: "^anonymous_enable=YES"
        line: "anonymous_enable=NO"
      - regexp: "^#xferlog_file=/var/log/xferlog"
        line: "xferlog_file=/var/log/vsftpd.log"
      - regexp: "^xferlog_std_format=YES"
        line: "xferlog_std_format=NO"
      - regexp: "^#ftpd_banner=Welcome to blah FTP service"
        line: "ftpd_banner=Welcome to blah FTP service"
      - regexp: "^#chroot_local_user=YES"
        line: "chroot_local_user=YES"
      - regexp: "^#chroot_list_enable=YES"
        line: "chroot_list_enable=YES"
      - regexp: "^#chroot_list_file=/etc/vsftpd/chroot_list"
        line: "chroot_list_file=/etc/vsftpd/chroot_list"

  - name: 設定行の追加
    lineinfile:
      dest="/etc/vsftpd/vsftpd.conf"
      line={{ item }}
    with_items:
      - userlist_deny=NO
      - userlist_file=/etc/vsftpd/user_list
      - seccomp_sandbox=NO
      - allow_writeable_chroot=YES

  - name: restart vsftpd
  # vsftpdの再起動
    service: name=vsftpd state=restarted enabled=yes
    
