- hosts: localhost
  connection: local
  remote_user: root
  sudo: yes

  vars_prompt:
  - name: yum_update
    prompt: "Do you accept updates ?"
    private: no
    default: Y

  tasks:
  - name: Yum update packages
    yum: name=* state=latest
    when: yum_update == "Y"

  - name: Disabled SELinux
    replace: >-
      dest="/etc/selinux/config"
      regexp="SELINUX=enforcing"
      replace="SELINUX=disabled"
    
  - name: Install ZABBIX reopsitory
    yum: name={{ item }}
    with_items:
      - http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm

  - name: install the 'Development tools' package group
    yum: name="{{ item }}" state=present
    with_items:
      - "@Development tools"
      - make
      - mock
      - wget
      - glib2-devel
      - gtk2-devel
      - pam-devel
      - libcap-devel
      - openssl-devel
      - tcp_wrappers-devel
      - nkf
      - perl-CGI
      - perl-URI
      - telnet
      - wget
      - ftp
      - nmap
      - traceroute
  
  - name: install the Zabbix Agent
    yum: name="{{ item }}" state=present
    with_items:
      - zabbix-agent
      - zabbix-get

  - name: install the cronie-noanacron package
    yum: name=cronie-noanacron state=latest
    
  - name: remove the cronie-anacron package
    yum: name=cronie-anacron state=absent
  
  - name: remove the postfix package
    yum: name=postfix state=absent
  
  - name: Create mockbuild user
    command: useradd -s /sbin/nologin mockbuild

  - name: Create sftp log
    command: cp /dev/null /var/log/sftp

  - name: rsyslog.conf setting
    lineinfile:
      dest=/etc/rsyslog.conf
      insertafter="^local7.*"
      line={{ item }}
    with_items:
      - "local5.* /var/log/sftp"
      - "# This rule to save the log output of sftp"
      - " "
      
  - name: sshd setting
    # /etc/ssh/sshd_configの設定変更
    lineinfile:
      dest="/etc/ssh/sshd_config"
      state=present
      backrefs=yes
      regexp='{{ item.regexp }}'
      line='{{ item.line }}'
    with_items:
      - regexp: "^Subsystem"
        line: "Subsystem       sftp    /usr/libexec/openssh/sftp-server -f LOCAL5 -l VERBOSE"
      - regexp: "^GSSAPIAuthentication yes"
        line: "GSSAPIAuthentication no"        
      - regexp: "^#UseDNS yes"
        line: "UseDNS no"        

  - name: logrotate setting
    lineinfile:
      dest=/etc/logrotate.d/syslog
      insertafter='^/var/log/spooler'
      line={{ item }}
    with_items:
      - /var/log/sftp
      
  - name: Install EDI services
    yum: name="{{ item }}" state=present
    with_items:
      - vsftpd
      - open-vm-tools
      
  - name: Backup vsftpd.conf
    command: cp /etc/vsftpd/vsftpd.conf /etc/vsftpd/vsftpd.conf.orig

  - name: Create chroot_list
    command: cp /dev/null /etc/vsftpd/chroot_list
 
  - name: vsftpd setting
    # /etc/vsftpd/vsftpd.confの設定変更
    lineinfile:
      dest="/etc/vsftpd/vsftpd.conf"
      state=present
      backrefs=yes
      regexp='{{ item.regexp }}'
      line='{{ item.line }}'
    with_items:
      - regexp: "^anonymous_enable=YES"
        line: "anonymous_enable=NO"
      - regexp: "^#xferlog_file=/var/log/xferlog"
        line: "xferlog_file=/var/log/vsftpd.log"
      - regexp: "^xferlog_std_format=YES"
        line: "xferlog_std_format=NO"
      - regexp: "^#ftpd_banner=Welcome to blah FTP service"
        line: "ftpd_banner=Welcome to blah FTP service"
      - regexp: "^#chroot_local_user=YES"
        line: "chroot_local_user=YES"
      - regexp: "^#chroot_list_enable=YES"
        line: "chroot_list_enable=YES"
      - regexp: "^#chroot_list_file=/etc/vsftpd/chroot_list"
        line: "chroot_list_file=/etc/vsftpd/chroot_list"
      - regexp: "^listen=NO"
        line: "listen=YES"
      - regexp: "^listen_ipv6=YES"
        line: "listen_ipv6=NO"
      - regexp: "^tcp_wrappers=YES"
        line: "tcp_wrappers=NO"
  
  - name: add line vsftpd.conf
    lineinfile:
      dest="/etc/vsftpd/vsftpd.conf"
      line={{ item }}
    with_items:
      - pasv_enable=YES
      - userlist_deny=NO
      - userlist_file=/etc/vsftpd/user_list
      - seccomp_sandbox=NO
      - allow_writeable_chroot=YES
      - use_localtime=YES
      
  - name: restart vsftpd
  # vsftpdの再起動
    service: name=vsftpd state=restarted enabled=yes
    
  - name: restart sshd
  # sshdの再起動
    service: name=sshd state=restarted

  - name: restart rsyslog
  # rsyslogの再起動
    service: name=rsyslog state=restarted

  # firewall setting
  - firewalld: service=ftp permanent=true state=enabled immediate=true
  - firewalld: port=10050-10051/tcp permanent=true state=enabled immediate=true
  
  # logrotate設定
  - name: logrotation setting
    command: mv /etc/logrotate.conf /etc/logrotate.conf.orig
    command: cp /root/ansible-edi-rhel7/logrotate.conf /etc/logrotate.conf
  
  - name: cron setting
    # /etc/cron.d/dailyjobsの設定変更
    lineinfile:
      dest="/etc/cron.d/dailyjobs"
      state=present
      backrefs=yes
      regexp='{{ item.regexp }}'
      line='{{ item.line }}'
    with_items:
      - regexp: "^02 4 * * * root [ ! -f /etc/cron.hourly/0anacron ] && run-parts /etc/cron.daily"
        line: "00 0 * * * root [ ! -f /etc/cron.hourly/0anacron ] && run-parts /etc/cron.daily"
        
